# This file was generated by WriteXDCFile from collected XDCAnnotations.

set_property RAM_STYLE ULTRA [get_cells firesim_top/top/CPUManagedStreamEngine_0/TRACERVBRIDGEMODULE_0_to_cpu_stream_outgoingQueueIO_q/ram_reg*]