# This file was generated by WriteXDCFile from collected XDCAnnotations.

create_generated_clock -name uart_clock,clock_1000.0MHz,harnessbinder_clock,reference -source [get_pins -of [get_clocks host_clock]] [get_pins Top_i/firesim_wrapper_0/inst/firesim_top/top/sim/target/FireSim_/clockBridge_clocks_0_buffer/O] -divide_by 1
set_multicycle_path 1 -setup -from [get_clocks uart_clock,clock_1000.0MHz,harnessbinder_clock,reference] -to [get_clocks uart_clock,clock_1000.0MHz,harnessbinder_clock,reference]
set_multicycle_path 0 -hold  -from [get_clocks uart_clock,clock_1000.0MHz,harnessbinder_clock,reference] -to [get_clocks uart_clock,clock_1000.0MHz,harnessbinder_clock,reference]
